### ISSUE TITLE
Feature: User can choose a league 

### ISSUE THREAD

**Issue by udaibirv** [udaibirv/footyVerse#3]
## ⚙️ Feature

> ##### User can choose which league they want to follow (acts as a landing page from user-login) 

## 📐 Functionality

> ##### User will be able to click on the image of any of the top 5 European Leagues (England, Germany, Italy, France, Spain) with description of each league. This will take them to a page with all of the league info (separate feature) 

## ✅ Task List

> #####

- [x] Test "x-apisports" to ensure I am getting the right information for each league 
- [x] Get the image of each league's logo and wrap it within an anchor tag so that it can redirect user to each league's own component 
- [x] Write a basic description of each league
