### ISSUE TITLE
User can view league-info 

### ISSUE THREAD

**Issue by udaibirv** [udaibirv/footyVerse#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on a card and view in depth information about a specific league

## 📐 Functionality

The user will be able to see info such as league standings, and team stats for the league they choose, (England, Germany, etc)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the first league component (England) 
- [x] Create dropdown so user can choose a specific season 
- [x] make a call to the football API with the user inputted date and render the league table
